# Generated by Django 5.0.4 on 2024-04-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_remove_expense_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-amount']},
        ),
        migrations.AlterField(
            model_name='expense',
            name='item',
            field=models.CharField(max_length=30),
        ),
    ]
